services:
  postgres:
    restart: on-failure
    ports:
      - "${AKL_DEV_POSTGRES_PORT:-5432}:5432"
  minio:
    restart: on-failure
    ports:
      - "${AKL_DEV_MINIO_API_PORT:-9000}:9000"
      - "${AKL_DEV_MINIO_CONSOLE_PORT:-9001}:9001"
  qdrant:
    restart: on-failure
    ports:
      - "${AKL_DEV_QDRANT_HTTP_PORT:-6333}:6333"
      - "${AKL_DEV_QDRANT_GRPC_PORT:-6334}:6334"
  airflow-webserver:
    ports:
      - "${AKL_DEV_AIRFLOW_PORT:-8080}:8080"
  grafana:
    ports:
      - "${AKL_DEV_GRAFANA_PORT:-3000}:3000"
  prometheus:
    ports:
      - "${AKL_DEV_PROMETHEUS_PORT:-9090}:9090"
  mlflow:
    ports:
      - "${AKL_DEV_MLFLOW_PORT:-5000}:5000"
